### ISSUE TITLE
descale: Add `descaled_height` prop

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-scale#1]
It'd be nice if there was a way to check what resolution the clip was descaled to when given two or more native resolutions. I think a frameprop is the least intrusive way to do so.

**Comment by Setsugennoao** [comment]
It already does that

**Comment by Setsugennoao** [comment]
https://github.com/Irrational-Encoding-Wizardry/vs-scale/blob/master/vsscale/descale.py#L286
https://github.com/Irrational-Encoding-Wizardry/vs-scale/blob/master/vsscale/types.py#L105
