### ISSUE TITLE
Descale: Hardcode SAR or take from input clip if close enough

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-scale#15]
Currently, post-descaling, the SAR is set to be non-1:1

![image](https://user-images.githubusercontent.com/42927908/206882144-686d4703-dac1-4447-87a8-c8bdd37591f7.png)

Given that you'd only ever descale a source that is both already progressive and highly unlikely to ever be non-1:1, it might not be a bad idea to either hardcode the SAR to 1:1, or to take it from the input clip (assuming the output resolution is close enough to it).

Alternatively, leave it and tell the user to suck it and pay better attention :^)))))

**Comment by Setsugennoao** [comment]
I mean, shouldn't descale just copy the frame props for the upscaled clip anyways? it doesn't add any
and if there are added, they should be gotten from descaled/rescaled clip with result=True.
Updated behaviour in https://github.com/Irrational-Encoding-Wizardry/vs-scale/commit/24100045198c82cf61b6ec00cb9ec06818770398
