### ISSUE TITLE
Linemasking post-rescale

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-scale#16]
A good additional operation to have for rescaling might be to mask it to lineart. This is a fairly standard rescaling operation as it reduces damage to grain and the like. Ergo, it would be nice if `descale` did this internally. Maybe worth looking at once you finish your vsmask rewrite?

**Comment by Setsugennoao** [comment]
You can already do this, though it might not be super intuitive, through the mask param
You just have to pass an inverted mask

**Comment by LightArrowsEXE** [comment]
Doesn't this override regular credit masking, however?

**Comment by Setsugennoao** [comment]
Yeah
I will make the mask param a tuple with the first element being the error mask, the second being post-processing like linemasking
