### ISSUE TITLE
Use `vskernels.Bicubic` for kernel/scaler params where applicable

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-scale#65]
For clarity, it might be nice to use `Bicubic` instead of named kernels such as `Catrom`. This way, it's clearer to your average user what exact values are being passed. This might also be extendible to stuff like default `Lanczos` calls by adding `taps=3`, and potentially other similar kernels.

**Comment by Setsugennoao** [comment]
NO. I also changed back all of these instances in lvsfunc if you didn't notice.

![](https://cdn.discordapp.com/emojis/805663853069205544.gif?size=32&quality=lossless)

**Comment by LightArrowsEXE** [comment]
If it weren't for the laws of this land, I would've slaughtered you.
