### ISSUE TITLE
Add a resizer similar to Avisynth's CropResize

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-scale#75]
It's possible to do resizing with zero aspect ratio error by utilizing subpixel cropping, a way to handle this automatically would be very useful.

**Comment by NSQY** [comment]
https://forum.doom9.org/showthread.php?p=1991790#post1991790

**Comment by wiwaz** [comment]
implemented myself here [https://gist.github.com/wiwaz/7d5afee6aadb1dae0131aedc6d1a6440](https://gist.github.com/wiwaz/7d5afee6aadb1dae0131aedc6d1a6440)

**Comment by wiwaz** [comment]
Additionally, this is more fit for vskernels and just having an argument such as `keepaspect` to enable this behavior. It's almost always desirable over distorting the aspect ratio so maybe it should be default, too.

**Comment by Setsugennoao** [comment]
how would this work when you're specifying your own shift/src_xxx

**Comment by Setsugennoao** [comment]
Fixed here https://github.com/Irrational-Encoding-Wizardry/vs-kernels/commit/e94adb93fe02f4a46b25b442fa4642e7d1affa6b
