### ISSUE TITLE
Waifu2x does not set fp16=False when cuda=True

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-scale#79]
Results in error thrown.

**Comment by Setsugennoao** [comment]
yap

**Comment by BReza27** [comment]
#juice squad

**Comment by Setsugennoao** [comment]
https://github.com/Irrational-Encoding-Wizardry/vs-scale/commit/1eb4be443b08763b49a606d2ed1bbd7c33fc03e9
