### ISSUE TITLE
keep_ar has wrong output, does not match crop_resize script

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-scale#83]
[example](https://slow.pics/c/sKkc9vYY)

```py
wrong = vskernels.Catrom.scale(clip, width=1920, height=804, src_height=1606, src_top=277, keep_ar=True)
correct = crop_resize(clip, width=1920, height=804, src_height=1606, src_top=277)

**Comment by wiwaz** [comment]
fixed by [https://github.com/Irrational-Encoding-Wizardry/vs-kernels/commit/23de3877a27fd3fe877f14059c3a6121ff168ac2](#23de387)

**Comment by Setsugennoao** [comment]
for the record, was just preferring shift parameter over kwargs
